### PR TITLE
kpi: update modules

### PR DESCRIPTION
**Pull request by Lodifice**
This is currently deployed on staging and seems to be accepted.

### CODE REVIEW

**Comment by inyono** [comment]
aggregator-cronjob has CrashLoopBackOff:
```
/tmp/aggregator.sql:80: ERROR: INSERT has more expressions than target columns
LINE 7: count(author_active_teacher) as "active teachers"
```

**Comment by Lodifice** [comment]
Due to the large amount of changes it would be best to wipe the KPI database and let it be recreated by the aggregator.

For newer versions, the aggregator can do that by itself.

**Comment by inyono** [comment]
Still the same issue after wiping the DB & running mysql-importer (succeeded).

**Comment by Lodifice** [comment]
This is very strange, as the table is created with 5 columns at line 41 and then there is the insert of 5-tuples into that table until line 80.

Can you please post the schema description (`\d+ cache_active_authors`)? Besides that it's hard to debug, as I don't have access to the database.

**Comment by inyono** [comment]
Only four columns:

| column\_name | data\_type | character\_maximum\_length |
| :--- | :--- | :--- |
| time | date | NULL |
| authors | integer | NULL |
| active\_authors | integer | NULL |
| very\_active\_authors | integer | NULL |

`very_active_teachers` seems to be missing.

**Comment by inyono** [comment]
Nevermind, dropped the tables again (maybe I did something wrong the first time) and now it works.

**Pull request merged**
